
services:
  kali:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: kasm_kali
    restart: unless-stopped
    shm_size: 512m
    environment:
      - VNC_PW=${password}
    ports:
      - "6901:6901"
    volumes:
      - ./Shared:/home/kasm-user/
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
