version: "3.7"

services:
  kali:
    image: 0d810ab84d78
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: kasm_kali
    restart: unless-stopped
    shm_size: 512m
    environment:
      - VNC_PW=password
    ports:
      - "6901:6901"
    cap_add:
      - NET_ADMIN
# {"cap_add":["NET_ADMIN"],"devices":["dev/net/tun","/dev/net/tun"],"sysctls":{"net.ipv6.conf.all.disable_ipv6":"0"}}
