version: "3.7"

services:
  kali:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: kali
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    hostname: kali
    environment:
      - DISPLAY=host.docker.internal:0
      - TERM=xterm-256color
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN